# -*- coding: utf-8 -*-
"""Data Analysis Graphs.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/17TnoYFRQsg9S7b2TaZ3gQriZrE7uSlwq
"""

import matplotlib.pyplot as plt

import pandas as pd

df=pd.read_csv("/content/pie chart1 - Sheet1.csv")

df

# defining the slice with the highest percentage
explode = [0.1 if p == df['Percentage'].max() else 0 for p in df['Percentage']]

# Creating a pie chart with both percentage and frequency labels
plt.figure(figsize=(8, 8))
wedges, texts, autotexts = plt.pie(df['Percentage'], labels=df.apply(lambda x: f"{x['Survey response']} ({x['Percentage']:.1f}%)", axis=1),
        autopct='', startangle=90, explode=explode, shadow=True, colors=plt.cm.Paired.colors,wedgeprops=dict(edgecolor='black'))

# Adding corresponding frequencies as txt labels inside the pie chart
for autotext, freq in zip(autotexts, df['Frequency']):
    autotext.set_text(f'{freq}')

# Increasing the size of frequency labels inside the pie chart
for autotext in autotexts:
    autotext.set_size(8)


plt.title('Pie chart of responses')


plt.show()

df=pd.read_csv('AH_Excess_Deaths_by_Sex__Age__and_Race_and_Hispanic_Origin.csv')

df

country=df['Geography'].unique()

country



df1 = df[(df['MMWRweek'] <= 34) & (df['MMWRyear'] >= 2018)]

df1.shape

df1.head(5)

# Group by 'year' and sum the 'deaths' for each year
total_deaths_per_year = df1.groupby('MMWRyear')['Deaths (weighted)'].sum().reset_index()

df2=total_deaths_per_year

df2

# Defining colors for each bar
bar_colors = ['blue']

# Creating a horizontal bar graph with different colors
plt.figure(figsize=(10, 6))
bars = plt.barh(df2['MMWRyear'], df2['Deaths (weighted)'], color=bar_colors)

# Labeling axes
plt.xlabel('Total deaths in the USA in the week 1-34')
plt.ylabel('Years')


plt.title('Strange pandamic : More deaths in Ending Year')

# Adding values inside and near the end points of the bars
for bar in bars:
    plt.text(bar.get_width() - 5, bar.get_y() + bar.get_height() / 2,
             f'{bar.get_width()}',
             va='center', ha='right', color='white')

# Show the plot
plt.show()

df

df.head(30000)

df.head()

df['AgeGroup'].unique()

df3=df[(df['MMWRyear'] <= 2020 ) & (df['AgeGroup'] == '15-19 Years')]

df3

# Calculating total deaths per year
total_deaths_per_year = df3.groupby('MMWRyear')['Deaths (weighted)'].sum().reset_index()

# adding colors for each bar
bar_colors = ['blue']

# Creating a vertical bar graph with different colors
plt.figure(figsize=(10, 6))
bars = plt.bar(total_deaths_per_year['MMWRyear'], total_deaths_per_year['Deaths (weighted)'], color=bar_colors, edgecolor='black')

# Labeling axes
plt.xlabel('Year')
plt.ylabel('Total Deaths')


plt.title('Non-Covid Deaths in US: 15-19 years age group')

# Adding values on top of the bars
for bar in bars:
    plt.text(bar.get_x() + bar.get_width() / 2, bar.get_height(),
             f'{bar.get_height()}',
             va='bottom', ha='center', color='black', fontsize=10)


plt.show()

